print("Creating your custom ID Card: Please enter the following information.")
Firstname = input("First name:")
Lastname = input("Last name:")
Email = input("Email address:")
Phone = input("Phone number:")
Jobtitle = input("Job title:")
ID = input("ID number:")
Eyes = input("What is your eye's color? ")
Hair = input("What is your hair's color? ")
Month = input("Which month were you born? ")
Training = input("Are you training? ")
print(" ")
print("The ID Card is:")
print(" ")
print(Lastname.upper() + ", " + Firstname.capitalize())
print(Jobtitle.title())
print("ID: " + ID)
print(" ")
print(Email.lower())
print(Phone)
print(" ")
print(f"Hair: {Hair:15} Eyes: {Eyes}")
print(f"Month: {Month:14} Training: {Training}")
print("----------------------------------------")
