print("Creating your custom ID Card: Please enter the following information.")
Firstname = input("First name:")
Lastname = input("Last name:")
Email = input("Email address:")
Phone = input("Phone number:")
Jobtitle = input("Job title:")
ID = input("ID number:")
print(" ")
print("The ID Card is:")
print(" ")
print(Lastname.upper() + ", " + Firstname.capitalize())
print(Jobtitle.title())
print("ID: " + ID)
print(" ")
print(Email.lower())
print(Phone)
print(" ")
