print('Dados da primeira pessoa:')
nome1 = str(input('Nome: '))
idade1 = int(input('Idade: '))
print('')
print('Dados da segunda pessoa:')
nome2 = str(input('Nome: '))
idade2 = int(input('Idade: '))
print('')
resultado = (idade1 + idade2) / 2
print(f'A idade média de {nome1} e {nome2} é de {resultado:.0f} anos.')