print("Hi there!")
name = input ("What is your name?") 
print("Let's find out which color is your favorite.")
color = input("Type here your favorite color:")
print(f"{name} ,Your favorite color according to our research is {color}"". Congratulations! It is a beautiful color.")
